-- =====================================================
-- SUN BOOKING TOURS
-- PostgreSQL Database Schema
-- =====================================================

-- =====================================================
-- USER / ACCOUNT
-- =====================================================

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR,
    password VARCHAR,
    full_name VARCHAR,
    email VARCHAR NOT NULL,
    phone VARCHAR,
    avatar VARCHAR,
    role VARCHAR,
    status VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);


CREATE TABLE social_account (
    social_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    provider VARCHAR,
    provider_uid VARCHAR,
    created_at TIMESTAMP,

    CONSTRAINT fk_social_account_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);





-- =====================================================
-- CATEGORY
-- =====================================================

CREATE TABLE category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);


-- =====================================================
-- TOUR SYSTEM
-- =====================================================

CREATE TABLE tour (
    tour_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,

    name VARCHAR,
    description TEXT,
    base_price NUMERIC,

    departure VARCHAR,
    destination VARCHAR,
    duration VARCHAR,

    status VARCHAR,
    start_date TIMESTAMP,
    end_date TIMESTAMP,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_tour_category
        FOREIGN KEY (category_id)
        REFERENCES category(category_id)
);


CREATE TABLE tour_image (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT,

    image_url VARCHAR,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_tour_image_tour
        FOREIGN KEY (tour_id)
        REFERENCES tour(tour_id)
);


CREATE TABLE tour_departure (
    departure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT,

    departure_date DATE,
    return_date DATE,

    price NUMERIC,

    total_slot INTEGER,
    available_slot INTEGER,

    status VARCHAR,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_tour_departure_tour
        FOREIGN KEY (tour_id)
        REFERENCES tour(tour_id)
);


CREATE TABLE place (
    place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR,
    description TEXT,

    address VARCHAR,
    city VARCHAR,

    image_url VARCHAR,
    status VARCHAR,

    created_at TIMESTAMP,
    updated_at TIMESTAMP
);


CREATE TABLE tour_place (
    tour_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tour_id BIGINT,
    place_id BIGINT,

    day_number INTEGER,
    visit_order INTEGER,

    description TEXT,

    created_at TIMESTAMP,

    CONSTRAINT fk_tour_place_tour
        FOREIGN KEY (tour_id)
        REFERENCES tour(tour_id),

    CONSTRAINT fk_tour_place_place
        FOREIGN KEY (place_id)
        REFERENCES place(place_id)
);


CREATE TABLE food (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT,

    name VARCHAR,
    description TEXT,
    price NUMERIC,

    image_url VARCHAR,
    status VARCHAR,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_food_place
        FOREIGN KEY (place_id)
        REFERENCES place(place_id)
);


-- =====================================================
-- BOOKING / PAYMENT
-- =====================================================

CREATE TABLE booking (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT,
    departure_id BIGINT,

    booking_date TIMESTAMP,

    number_of_people INTEGER,
    total_price NUMERIC,

    contact_name VARCHAR,
    contact_phone VARCHAR,
    contact_email VARCHAR,

    status VARCHAR,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_booking_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_booking_departure
        FOREIGN KEY (departure_id)
        REFERENCES tour_departure(departure_id)
);


CREATE TABLE booking_traveler (
    traveler_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT,

    full_name VARCHAR,
    gender VARCHAR,
    date_of_birth DATE,

    phone VARCHAR,
    traveler_type VARCHAR,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_booking_traveler_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id)
);


CREATE TABLE payment (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT,

    amount NUMERIC,

    payment_method VARCHAR,
    transaction_code VARCHAR,

    payment_date TIMESTAMP,
    status VARCHAR,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_payment_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id)
);


-- =====================================================
-- REVIEW / INTERACTION
-- =====================================================

CREATE TABLE review (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT,

    content TEXT,
    rating INTEGER,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_review_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking(booking_id),

    -- ERD:
    -- BOOKING.booking_id - REVIEW.booking_id
    -- represents one review per booking
    CONSTRAINT uq_review_booking
        UNIQUE (booking_id)
);


CREATE TABLE review_image (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id BIGINT,

    image_url VARCHAR,

    created_at TIMESTAMP,

    CONSTRAINT fk_review_image_review
        FOREIGN KEY (review_id)
        REFERENCES review(review_id)
);


CREATE TABLE review_like (
    like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id BIGINT,
    user_id BIGINT,

    created_at TIMESTAMP,

    CONSTRAINT fk_review_like_review
        FOREIGN KEY (review_id)
        REFERENCES review(review_id),

    CONSTRAINT fk_review_like_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);


CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id BIGINT,
    user_id BIGINT,
    parent_comment_id BIGINT,

    content TEXT,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_comment_review
        FOREIGN KEY (review_id)
        REFERENCES review(review_id),

    CONSTRAINT fk_comment_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_comment_parent
        FOREIGN KEY (parent_comment_id)
        REFERENCES comments(comment_id)
);


-- =====================================================
-- NEWS
-- =====================================================

CREATE TABLE news (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    author_id BIGINT,

    title VARCHAR,
    summary TEXT,
    content TEXT,

    thumbnail_url VARCHAR,

    status VARCHAR,
    published_at TIMESTAMP,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_news_author
        FOREIGN KEY (author_id)
        REFERENCES users(user_id)
);


-- =====================================================
-- INDEXES FOR FOREIGN KEYS
-- =====================================================

CREATE INDEX idx_social_account_user_id
    ON social_account(user_id);



CREATE INDEX idx_tour_category_id
    ON tour(category_id);

CREATE INDEX idx_tour_image_tour_id
    ON tour_image(tour_id);

CREATE INDEX idx_tour_departure_tour_id
    ON tour_departure(tour_id);

CREATE INDEX idx_tour_place_tour_id
    ON tour_place(tour_id);

CREATE INDEX idx_tour_place_place_id
    ON tour_place(place_id);

CREATE INDEX idx_food_place_id
    ON food(place_id);

CREATE INDEX idx_booking_user_id
    ON booking(user_id);

CREATE INDEX idx_booking_departure_id
    ON booking(departure_id);

CREATE INDEX idx_booking_traveler_booking_id
    ON booking_traveler(booking_id);

CREATE INDEX idx_payment_booking_id
    ON payment(booking_id);



CREATE INDEX idx_review_image_review_id
    ON review_image(review_id);

CREATE INDEX idx_review_like_review_id
    ON review_like(review_id);

CREATE INDEX idx_review_like_user_id
    ON review_like(user_id);

CREATE INDEX idx_comment_review_id
    ON comments(review_id);

CREATE INDEX idx_comment_user_id
    ON comments(user_id);

CREATE INDEX idx_comment_parent_id
    ON comments(parent_comment_id);

CREATE INDEX idx_news_author_id
    ON news(author_id);