spring:
  application:
    name: sun-booking-tours
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: "optional:classpath:application-secret.yml"

server:
  port: 8080

app:
  jwt:
    expiration-ms: 86400000
  oauth2:
    authorized-redirect-uris: http://localhost:5173/oauth2/redirect
